# Generated by Django 4.0.1 on 2022-02-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='security_answer',
            new_name='s_answer',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='security_name',
            new_name='s_name',
        ),
    ]
