# Generated by Django 4.0.1 on 2022-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='s_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='s_name',
            field=models.CharField(choices=[('CITY', 'In what city were you born?'), ('PET', 'What is the name of your favorite pet?'), ('MAIDEN', "What is your mother's maiden name?"), ('SCHOOL', 'What is the name of your first school?'), ('CAR', 'What was the make of your first car?'), ('FOOD', 'What was your favorite food as a child?')], max_length=100),
        ),
    ]
