version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: |
      sh -c "python /app/manage.py wait_for_db &&
             python /app/manage.py migrate &&
             gunicorn -w 3 dr.wsgi:application --access-logfile access.txt --error-logfile errors.txt --reload"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=poiu0987
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=poiu0987
    ports:
      - "5432:5432"
