# Generated by Django 4.0.1 on 2022-01-22 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=240, verbose_name='Name')),
                ('model', models.CharField(max_length=240, verbose_name='Model')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Price')),
                ('entry', models.TextField(blank=True, default='', max_length=1000, verbose_name='Entry')),
                ('uuid_field', models.UUIDField(default=uuid.UUID('9c277776-37a4-4e58-9850-903b706dcdf6'), editable=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Item Listing Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Item Updated at')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='Slug')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
