# Generated by Django 4.0.1 on 2022-01-21 00:21

from django.db import migrations


def create_data(apps, schema_editor):
    Seller = apps.get_model('items', 'Seller')
    Seller(first_name="guney", last_name="bilen", nickname="gb", email="gb@gb.com", phone_number="1111111111").save()


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
