# Generated by Django 4.0.1 on 2022-01-22 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid_field',
            field=models.UUIDField(default=uuid.UUID('3f10f62d-3548-4825-b5c0-79e8aca45c8e'), editable=False),
        ),
    ]
