# Generated by Django 4.0.1 on 2022-02-07 04:02

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image1',
            field=models.ImageField(default=None, null=True, upload_to='images/', validators=[items.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image2',
            field=models.ImageField(default=None, null=True, upload_to='images/', validators=[items.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image3',
            field=models.ImageField(default=None, null=True, upload_to='images/', validators=[items.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price'),
        ),
    ]
