# Generated by Django 4.0.1 on 2022-01-22 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid_field',
            field=models.UUIDField(default=uuid.UUID('acde5871-27de-483e-a5c0-330917987870'), editable=False),
        ),
    ]
