# Generated by Django 4.0.1 on 2022-01-22 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_slug_alter_item_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid_field',
            field=models.UUIDField(default=uuid.UUID('32e98d71-0802-4bd6-9a9a-7e8aa33ab611'), editable=False),
        ),
    ]
