# Generated by Django 4.0.1 on 2022-01-23 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_slug_alter_item_uuid_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['createdAt']},
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid_field',
            field=models.UUIDField(default=uuid.UUID('7aaf4c13-12f7-481d-8560-021a60ef8c9f'), editable=False),
        ),
    ]
