# Generated by Django 4.0.1 on 2022-01-23 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_options_alter_item_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid_field',
            field=models.UUIDField(default=uuid.UUID('675c3bb9-50a6-4fe1-a5f3-df16262a7e77'), editable=False),
        ),
    ]
