# Generated by Django 4.0.1 on 2022-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid_field',
            field=models.UUIDField(),
        ),
    ]
